-- SQL Data Quality Engineering
-- PostgreSQL-compatible demonstration.
--
-- The model represents a retail ingestion domain and deliberately includes
-- imperfect records so that each quality rule can be observed.
--
-- The four major quality dimensions are separated:
--   duplicate detection       -> business identity collisions
--   missing values            -> completeness failures
--   referential integrity     -> invalid parent-child relationships
--   anomaly detection         -> statistically unusual observations
--
-- Run this script in PostgreSQL.

DROP SCHEMA IF EXISTS sql_data_quality CASCADE;
CREATE SCHEMA sql_data_quality;
SET search_path TO sql_data_quality;

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT,
    email TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT customers_name_not_blank
        CHECK (full_name IS NULL OR btrim(full_name) <> ''),

    CONSTRAINT customers_email_not_blank
        CHECK (email IS NULL OR btrim(email) <> '')
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    amount NUMERIC(14, 2) NOT NULL,
    order_date DATE NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT orders_positive_amount
        CHECK (amount > 0),

    CONSTRAINT orders_valid_status
        CHECK (
            status IN (
                'pending',
                'paid',
                'cancelled',
                'refunded'
            )
        ),

    CONSTRAINT orders_customer_fk
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- This index supports normalized business-identity searches. It is not made
-- UNIQUE because the purpose of this demonstration is to detect historical
-- duplicates rather than prevent every future duplicate at ingestion time.
CREATE INDEX idx_customers_normalized_identity
    ON customers (
        lower(btrim(email)),
        lower(btrim(full_name))
    );

CREATE INDEX idx_orders_customer_date
    ON orders (customer_id, order_date);

CREATE INDEX idx_orders_amount
    ON orders (amount);

INSERT INTO customers
    (customer_id, full_name, email, phone)
VALUES
    (1, 'Asha Verma', 'asha@example.com', '9876500001'),
    (2, 'Ravi Kumar', 'ravi@example.com', '9876500002'),
    (3, 'Ravi Kumar', 'ravi@example.com', '9876500002'),
    (4, 'Meera Shah', NULL, '9876500004'),
    (5, 'Unknown Customer', 'meera2@example.com', NULL),
    (6, 'Kabir Singh', 'kabir@example.com', '9876500006'),
    (7, 'Nisha Rao', 'nisha@example.com', '9876500007'),
    (8, 'Omar Khan', 'omarkhan@example.com', '9876500008');

INSERT INTO orders
    (order_id, customer_id, amount, order_date, status)
VALUES
    (101, 1, 120.50, DATE '2026-10-01', 'paid'),
    (102, 2, 80.00, DATE '2026-10-01', 'paid'),
    (103, 2, 75.00, DATE '2026-10-01', 'paid'),
    (104, 2, 70.00, DATE '2026-10-01', 'paid'),
    (105, 2, 65.00, DATE '2026-10-01', 'paid'),
    (106, 2, 55.00, DATE '2026-10-01', 'paid'),
    (107, 6, 150.00, DATE '2026-10-02', 'pending'),
    (108, 7, 210.00, DATE '2026-10-02', 'paid'),
    (109, 8, 9999.00, DATE '2026-10-02', 'paid'),
    (110, 1, 95.00, DATE '2026-10-03', 'cancelled');

-- =====================================================================
-- Completeness profiling
-- =====================================================================

CREATE OR REPLACE VIEW customer_completeness_profile AS
SELECT
    COUNT(*) AS total_customers,
    COUNT(full_name) AS populated_names,
    COUNT(email) AS populated_emails,
    COUNT(phone) AS populated_phones,
    COUNT(*) FILTER (
        WHERE full_name IS NULL
    ) AS missing_names,
    COUNT(*) FILTER (
        WHERE email IS NULL
    ) AS missing_emails,
    COUNT(*) FILTER (
        WHERE phone IS NULL
    ) AS missing_phones
FROM customers;

SELECT *
FROM customer_completeness_profile;

-- Field-level missing-value audit. A NULL email is not interchangeable with
-- a blank string, so both conditions are explicitly checked where necessary.
SELECT
    customer_id,
    'full_name' AS column_name
FROM customers
WHERE full_name IS NULL OR btrim(full_name) = ''

UNION ALL

SELECT
    customer_id,
    'email'
FROM customers
WHERE email IS NULL OR btrim(email) = ''

UNION ALL

SELECT
    customer_id,
    'phone'
FROM customers
WHERE phone IS NULL OR btrim(phone) = ''

ORDER BY customer_id, column_name;

-- =====================================================================
-- Duplicate detection
-- =====================================================================

-- Surrogate customer_id values cannot identify business duplicates.
-- Normalizing email and name makes the comparison insensitive to case and
-- accidental leading/trailing whitespace.
WITH duplicate_groups AS (
    SELECT
        lower(btrim(email)) AS normalized_email,
        lower(btrim(full_name)) AS normalized_name,
        COUNT(*) AS occurrence_count,
        ARRAY_AGG(customer_id ORDER BY customer_id) AS customer_ids
    FROM customers
    WHERE email IS NOT NULL
      AND btrim(email) <> ''
    GROUP BY
        lower(btrim(email)),
        lower(btrim(full_name))
    HAVING COUNT(*) > 1
)
SELECT
    normalized_email,
    normalized_name,
    occurrence_count,
    customer_ids
FROM duplicate_groups
ORDER BY occurrence_count DESC;

-- Detect duplicate emails even when the names differ. This is a separate
-- rule because an email collision and an identical business identity do not
-- necessarily mean the same thing.
SELECT
    lower(btrim(email)) AS normalized_email,
    COUNT(*) AS customer_count,
    ARRAY_AGG(customer_id ORDER BY customer_id) AS customer_ids
FROM customers
WHERE email IS NOT NULL
GROUP BY lower(btrim(email))
HAVING COUNT(*) > 1
ORDER BY customer_count DESC;

-- =====================================================================
-- Referential integrity
-- =====================================================================

-- PostgreSQL's foreign key prevents new invalid child rows. This query is
-- still useful for auditing legacy data imported while constraints were
-- disabled in another system.
SELECT
    o.order_id,
    o.customer_id
FROM orders AS o
LEFT JOIN customers AS c
    ON c.customer_id = o.customer_id
WHERE c.customer_id IS NULL;

-- The following statement is intentionally commented out because PostgreSQL
-- should reject it through orders_customer_fk:
--
-- INSERT INTO orders (order_id, customer_id, amount, order_date, status)
-- VALUES (999, 99999, 100.00, DATE '2026-10-05', 'paid');

-- =====================================================================
-- Deterministic domain validation
-- =====================================================================

SELECT
    order_id,
    amount,
    order_date,
    status
FROM orders
WHERE amount <= 0
   OR order_date IS NULL
   OR status NOT IN (
        'pending',
        'paid',
        'cancelled',
        'refunded'
   );

-- =====================================================================
-- Anomaly detection with distribution statistics
-- =====================================================================

-- PostgreSQL percentile_cont calculates exact interpolated percentiles.
-- The IQR rule is appropriate when the distribution is skewed and extreme
-- values should be identified without assuming normality.
WITH amount_statistics AS (
    SELECT
        percentile_cont(0.25)
            WITHIN GROUP (ORDER BY amount) AS q1,
        percentile_cont(0.50)
            WITHIN GROUP (ORDER BY amount) AS median_amount,
        percentile_cont(0.75)
            WITHIN GROUP (ORDER BY amount) AS q3
    FROM orders
    WHERE amount > 0
),
bounds AS (
    SELECT
        q1,
        median_amount,
        q3,
        q3 - q1 AS iqr,
        q3 + 1.5 * (q3 - q1) AS upper_fence
    FROM amount_statistics
)
SELECT
    o.order_id,
    o.amount,
    b.q1,
    b.median_amount,
    b.q3,
    b.iqr,
    b.upper_fence,
    CASE
        WHEN o.amount > b.upper_fence THEN 'ANOMALY'
        ELSE 'NORMAL'
    END AS classification
FROM orders AS o
CROSS JOIN bounds AS b
ORDER BY o.amount DESC;

-- =====================================================================
-- Customer-relative anomaly detection
-- =====================================================================

-- A value can be normal globally but abnormal for one customer. Window
-- functions therefore calculate each customer's historical average and rank.
WITH customer_statistics AS (
    SELECT
        customer_id,
        order_id,
        amount,
        AVG(amount) OVER (
            PARTITION BY customer_id
        ) AS customer_average,
        COUNT(*) OVER (
            PARTITION BY customer_id
        ) AS customer_order_count,
        ROW_NUMBER() OVER (
            PARTITION BY customer_id
            ORDER BY amount DESC
        ) AS amount_rank
    FROM orders
    WHERE status <> 'cancelled'
)
SELECT
    customer_id,
    order_id,
    amount,
    ROUND(customer_average, 2) AS customer_average,
    customer_order_count,
    amount_rank
FROM customer_statistics
WHERE amount > customer_average * 2
ORDER BY customer_id, amount DESC;

-- =====================================================================
-- Daily activity anomaly detection
-- =====================================================================

WITH daily_activity AS (
    SELECT
        customer_id,
        order_date,
        COUNT(*) AS daily_order_count
    FROM orders
    WHERE customer_id IS NOT NULL
    GROUP BY customer_id, order_date
),
activity_statistics AS (
    SELECT
        AVG(daily_order_count::NUMERIC) AS average_daily_orders,
        STDDEV_POP(daily_order_count::NUMERIC) AS stddev_daily_orders
    FROM daily_activity
)
SELECT
    d.customer_id,
    d.order_date,
    d.daily_order_count,
    ROUND(s.average_daily_orders, 2) AS average_daily_orders,
    ROUND(s.stddev_daily_orders, 2) AS stddev_daily_orders,
    CASE
        WHEN d.daily_order_count >
             s.average_daily_orders +
             3 * s.stddev_daily_orders
        THEN 'ANOMALY'
        ELSE 'NORMAL'
    END AS classification
FROM daily_activity AS d
CROSS JOIN activity_statistics AS s
ORDER BY d.daily_order_count DESC;

-- =====================================================================
-- Unified issue inventory
-- =====================================================================

CREATE TEMPORARY TABLE quality_issues (
    issue_id BIGINT GENERATED ALWAYS AS IDENTITY,
    rule_name TEXT NOT NULL,
    table_name TEXT NOT NULL,
    record_key TEXT NOT NULL,
    severity TEXT NOT NULL,
    detail TEXT NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO quality_issues
    (rule_name, table_name, record_key, severity, detail)
SELECT
    'duplicate_customer',
    'customers',
    customer_ids::TEXT,
    'HIGH',
    'Normalized email/name combination occurs multiple times.'
FROM (
    SELECT
        ARRAY_AGG(customer_id ORDER BY customer_id) AS customer_ids
    FROM customers
    WHERE email IS NOT NULL
    GROUP BY
        lower(btrim(email)),
        lower(btrim(full_name))
    HAVING COUNT(*) > 1
) AS duplicates;

INSERT INTO quality_issues
    (rule_name, table_name, record_key, severity, detail)
SELECT
    'missing_value',
    'customers',
    customer_id::TEXT,
    'MEDIUM',
    'Email is missing.'
FROM customers
WHERE email IS NULL OR btrim(email) = '';

INSERT INTO quality_issues
    (rule_name, table_name, record_key, severity, detail)
SELECT
    'orphan_order',
    'orders',
    o.order_id::TEXT,
    'CRITICAL',
    'Order references a nonexistent customer.'
FROM orders AS o
LEFT JOIN customers AS c
    ON c.customer_id = o.customer_id
WHERE c.customer_id IS NULL;

WITH amount_statistics AS (
    SELECT
        percentile_cont(0.25)
            WITHIN GROUP (ORDER BY amount) AS q1,
        percentile_cont(0.75)
            WITHIN GROUP (ORDER BY amount) AS q3
    FROM orders
    WHERE amount > 0
)
INSERT INTO quality_issues
    (rule_name, table_name, record_key, severity, detail)
SELECT
    'amount_anomaly',
    'orders',
    o.order_id::TEXT,
    'HIGH',
    format(
        'Amount %s exceeds IQR upper fence %s.',
        o.amount,
        ROUND((s.q3 + 1.5 * (s.q3 - s.q1))::NUMERIC, 2)
    )
FROM orders AS o
CROSS JOIN amount_statistics AS s
WHERE o.amount > s.q3 + 1.5 * (s.q3 - s.q1);

SELECT
    severity,
    COUNT(*) AS issue_count
FROM quality_issues
GROUP BY severity
ORDER BY
    CASE severity
        WHEN 'CRITICAL' THEN 1
        WHEN 'HIGH' THEN 2
        WHEN 'MEDIUM' THEN 3
        WHEN 'LOW' THEN 4
        ELSE 5
    END;

SELECT *
FROM quality_issues
ORDER BY detected_at, issue_id;

-- =====================================================================
-- Transactional remediation example
-- =====================================================================

-- A duplicate should not be removed by arbitrary deletion. The remediation
-- below changes the duplicate record's email after an explicit review.
-- The transaction makes it possible to validate the postcondition and roll
-- back if the intended quality condition is not achieved.

BEGIN;

UPDATE customers
SET email = 'ravi.kumar.duplicate@example.com'
WHERE customer_id = 3
  AND lower(btrim(email)) = 'ravi@example.com';

DO $$
DECLARE
    remaining_duplicates INTEGER;
BEGIN
    SELECT COUNT(*)
    INTO remaining_duplicates
    FROM (
        SELECT
            lower(btrim(email)),
            lower(btrim(full_name))
        FROM customers
        WHERE email IS NOT NULL
        GROUP BY
            lower(btrim(email)),
            lower(btrim(full_name))
        HAVING COUNT(*) > 1
    ) AS duplicate_groups;

    IF remaining_duplicates > 0 THEN
        RAISE EXCEPTION
            'Duplicate validation failed after remediation.';
    END IF;
END
$$;

COMMIT;

-- Verify the remediation.
SELECT
    lower(btrim(email)) AS normalized_email,
    lower(btrim(full_name)) AS normalized_name,
    COUNT(*) AS occurrence_count
FROM customers
WHERE email IS NOT NULL
GROUP BY
    lower(btrim(email)),
    lower(btrim(full_name))
HAVING COUNT(*) > 1;

-- =====================================================================
-- Performance inspection
-- =====================================================================

-- EXPLAIN (without ANALYZE) shows the optimizer's intended execution plan
-- without executing the query itself.
EXPLAIN
SELECT
    customer_id,
    full_name,
    email
FROM customers
WHERE lower(btrim(email)) = 'asha@example.com';

EXPLAIN
SELECT
    order_id,
    customer_id,
    amount
FROM orders
WHERE customer_id = 2
  AND order_date >= DATE '2026-10-01'
  AND order_date < DATE '2026-11-01';

-- =====================================================================
-- Data-quality governance principles represented by this schema
-- =====================================================================
--
-- A primary key prevents duplicate identifiers but cannot guarantee that two
-- customer records represent different real-world people.
--
-- NULL detection measures completeness, while CHECK constraints prevent some
-- classes of invalid values from entering the database.
--
-- A foreign key enforces structural integrity between parent and child data.
--
-- Statistical anomalies are not necessarily invalid records. An unusually
-- large order may be legitimate, so anomaly detection should normally create
-- an investigation signal rather than automatically delete the record.
--
-- Indexes improve repeated quality queries when their expressions and filter
-- predicates match the access patterns used by the workload.
