"""
Excel Pivot Tables: A Comprehensive Executable Study

This standalone script teaches and demonstrates the architecture and behavior of
Excel-style Pivot Tables using pure Python.

The implementation models:
    - Source/tabular data
    - Rows
    - Columns
    - Values
    - Filters
    - Aggregation functions
    - Grouping
    - Calculated fields
    - Drill-down
    - Grand totals and subtotals
    - Multiple value fields
    - Sorting and filtering
    - Missing values
    - Numeric and categorical data
    - Validation
    - Performance considerations
    - A reusable pivot-engine architecture

The examples use sales data so that the same concepts can be related directly
to practical Excel Pivot Table work.

No third-party packages are required.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date, datetime
from math import floor
from statistics import mean, median
from typing import Any, Callable, Iterable, Optional


# ---------------------------------------------------------------------------
# 1. FUNDAMENTAL CONCEPTS
# ---------------------------------------------------------------------------
#
# A Pivot Table does not normally change the underlying source records.
# Instead, it creates a summarized view by:
#
#   1. Choosing dimensions for Rows.
#   2. Choosing dimensions for Columns.
#   3. Choosing one or more measures for Values.
#   4. Optionally restricting records with Filters.
#   5. Applying aggregation functions such as SUM or COUNT.
#
# Example:
#
# Rows    = Region
# Columns = Product
# Values  = Sales
#
# The result answers:
#
# "How much did each region sell for each product?"
#
# The raw records remain unchanged.


@dataclass
class SalesRecord:
    """A single normalized source-table row."""

    order_id: str
    order_date: date
    region: str
    salesperson: str
    product: str
    category: str
    quantity: int
    unit_price: float
    unit_cost: float
    customer_type: str

    @property
    def sales(self) -> float:
        """Revenue generated by this transaction."""
        return self.quantity * self.unit_price

    @property
    def cost(self) -> float:
        """Estimated product cost."""
        return self.quantity * self.unit_cost

    @property
    def profit(self) -> float:
        """Revenue minus cost."""
        return self.sales - self.cost

    @property
    def profit_margin(self) -> float:
        """Profit as a percentage of revenue."""
        if self.sales == 0:
            return 0.0
        return self.profit / self.sales


# ---------------------------------------------------------------------------
# 2. SOURCE DATA
# ---------------------------------------------------------------------------

DATA = [
    SalesRecord("O001", date(2025, 1, 5), "North", "Asha", "Laptop", "Electronics", 2, 800, 600, "Retail"),
    SalesRecord("O002", date(2025, 1, 12), "North", "Rahul", "Phone", "Electronics", 5, 500, 350, "Corporate"),
    SalesRecord("O003", date(2025, 1, 18), "South", "Neha", "Desk", "Furniture", 3, 250, 150, "Retail"),
    SalesRecord("O004", date(2025, 2, 2), "South", "Vikram", "Chair", "Furniture", 10, 120, 70, "Corporate"),
    SalesRecord("O005", date(2025, 2, 9), "East", "Asha", "Laptop", "Electronics", 1, 850, 610, "Retail"),
    SalesRecord("O006", date(2025, 2, 16), "East", "Rahul", "Phone", "Electronics", 4, 520, 360, "Corporate"),
    SalesRecord("O007", date(2025, 3, 4), "West", "Neha", "Desk", "Furniture", 2, 270, 160, "Retail"),
    SalesRecord("O008", date(2025, 3, 11), "West", "Vikram", "Chair", "Furniture", 8, 125, 72, "Corporate"),
    SalesRecord("O009", date(2025, 3, 19), "North", "Asha", "Monitor", "Electronics", 6, 300, 210, "Retail"),
    SalesRecord("O010", date(2025, 4, 3), "South", "Rahul", "Laptop", "Electronics", 3, 820, 590, "Corporate"),
    SalesRecord("O011", date(2025, 4, 10), "East", "Neha", "Chair", "Furniture", 6, 130, 75, "Retail"),
    SalesRecord("O012", date(2025, 4, 22), "West", "Vikram", "Phone", "Electronics", 7, 510, 355, "Corporate"),
    SalesRecord("O013", date(2025, 5, 2), "North", "Asha", "Desk", "Furniture", 4, 260, 155, "Retail"),
    SalesRecord("O014", date(2025, 5, 17), "South", "Rahul", "Monitor", "Electronics", 5, 310, 215, "Corporate"),
    SalesRecord("O015", date(2025, 6, 7), "East", "Neha", "Laptop", "Electronics", 2, 840, 605, "Retail"),
    SalesRecord("O016", date(2025, 6, 21), "West", "Vikram", "Desk", "Furniture", 3, 255, 152, "Corporate"),
    SalesRecord("O017", date(2025, 7, 5), "North", "Asha", "Chair", "Furniture", 9, 118, 69, "Retail"),
    SalesRecord("O018", date(2025, 7, 14), "South", "Rahul", "Phone", "Electronics", 6, 515, 358, "Corporate"),
    SalesRecord("O019", date(2025, 8, 8), "East", "Neha", "Monitor", "Electronics", 3, 305, 212, "Retail"),
    SalesRecord("O020", date(2025, 8, 25), "West", "Vikram", "Laptop", "Electronics", 2, 830, 595, "Corporate"),
]


# ---------------------------------------------------------------------------
# 3. BASIC AGGREGATION FUNCTIONS
# ---------------------------------------------------------------------------

def aggregate_sum(values: Iterable[float]) -> float:
    """Equivalent conceptually to Excel's SUM."""
    return sum(values)


def aggregate_count(values: Iterable[Any]) -> int:
    """Counts supplied records/values."""
    return sum(1 for _ in values)


def aggregate_average(values: Iterable[float]) -> float:
    """Equivalent conceptually to Excel's AVERAGE."""
    materialized = list(values)
    return mean(materialized) if materialized else 0.0


def aggregate_min(values: Iterable[float]) -> Optional[float]:
    """Equivalent conceptually to Excel's MIN."""
    materialized = list(values)
    return min(materialized) if materialized else None


def aggregate_max(values: Iterable[float]) -> Optional[float]:
    """Equivalent conceptually to Excel's MAX."""
    materialized = list(values)
    return max(materialized) if materialized else None


def aggregate_distinct_count(values: Iterable[Any]) -> int:
    """
    Conceptually similar to Excel Data Model / Power Pivot distinct count.
    A normal Pivot Table and a Data Model Pivot Table have different
    capabilities around distinct counting.
    """
    return len(set(values))


AGGREGATIONS: dict[str, Callable[[Iterable[Any]], Any]] = {
    "sum": aggregate_sum,
    "count": aggregate_count,
    "average": aggregate_average,
    "min": aggregate_min,
    "max": aggregate_max,
    "distinct_count": aggregate_distinct_count,
}


# ---------------------------------------------------------------------------
# 4. FIELD ACCESS
# ---------------------------------------------------------------------------

def field_value(record: SalesRecord, field_name: str) -> Any:
    """
    Converts a Pivot Table field name into a value from the source record.

    This resembles Excel's field model:
        Region
        Product
        Sales
        Profit
        Quantity
        Order Date
    """
    normalized = field_name.strip().lower().replace(" ", "_")

    aliases = {
        "order_date": "order_date",
        "region": "region",
        "salesperson": "salesperson",
        "product": "product",
        "category": "category",
        "quantity": "quantity",
        "unit_price": "unit_price",
        "unit_cost": "unit_cost",
        "sales": "sales",
        "revenue": "sales",
        "cost": "cost",
        "profit": "profit",
        "profit_margin": "profit_margin",
        "customer_type": "customer_type",
    }

    if normalized not in aliases:
        raise KeyError(f"Unknown Pivot field: {field_name}")

    return getattr(record, aliases[normalized])


# ---------------------------------------------------------------------------
# 5. PIVOT CONFIGURATION
# ---------------------------------------------------------------------------

@dataclass
class ValueField:
    """
    Defines one field placed in Excel's Values area.

    Example:
        ValueField("Sales", "sum", "Total Sales")
    """

    field: str
    aggregation: str = "sum"
    label: Optional[str] = None

    def __post_init__(self) -> None:
        if self.aggregation not in AGGREGATIONS:
            raise ValueError(
                f"Unsupported aggregation '{self.aggregation}'. "
                f"Choose from: {', '.join(AGGREGATIONS)}"
            )

        if self.label is None:
            self.label = f"{self.aggregation.upper()} of {self.field}"


@dataclass
class PivotConfiguration:
    """
    Represents the logical architecture of a Pivot Table.

    rows:
        Fields used as row dimensions.

    columns:
        Fields used as column dimensions.

    values:
        Measures that are aggregated.

    filters:
        Record-level filtering rules.

    calculated_fields:
        Formula-like fields evaluated from each source record.
    """

    rows: list[str] = field(default_factory=list)
    columns: list[str] = field(default_factory=list)
    values: list[ValueField] = field(default_factory=list)
    filters: dict[str, set[Any]] = field(default_factory=dict)
    calculated_fields: dict[str, Callable[[SalesRecord], Any]] = field(
        default_factory=dict
    )


# ---------------------------------------------------------------------------
# 6. CALCULATED FIELDS
# ---------------------------------------------------------------------------
#
# An Excel calculated field creates a formula at the Pivot Table level.
#
# Example:
#
#   Profit = Sales - Cost
#
# This differs conceptually from simply adding a physical Profit column to
# the source table. Calculated fields operate through the Pivot Table's
# calculation model and have important Excel-specific limitations.
#
# The engine below models the useful conceptual behavior while keeping the
# implementation transparent.


def calculated_profit(record: SalesRecord) -> float:
    return record.sales - record.cost


def calculated_margin(record: SalesRecord) -> float:
    if record.sales == 0:
        return 0.0
    return record.profit / record.sales


def calculated_order_value_with_tax(record: SalesRecord) -> float:
    """Example calculated measure using a 18% illustrative tax rate."""
    return record.sales * 1.18


# ---------------------------------------------------------------------------
# 7. FILTERING
# ---------------------------------------------------------------------------

def apply_filters(
    records: Iterable[SalesRecord],
    filters: dict[str, set[Any]],
) -> list[SalesRecord]:
    """
    Apply Pivot-style report filters.

    Multiple allowed values for one field behave like OR.
    Different fields behave like AND.

    Example:
        Region in {"North", "South"}
        AND Customer Type == "Corporate"
    """
    filtered: list[SalesRecord] = []

    for record in records:
        accepted = True

        for field_name, allowed_values in filters.items():
            actual_value = field_value(record, field_name)

            if actual_value not in allowed_values:
                accepted = False
                break

        if accepted:
            filtered.append(record)

    return filtered


# ---------------------------------------------------------------------------
# 8. GROUPING
# ---------------------------------------------------------------------------

def month_group(value: date) -> str:
    """Group dates into calendar months."""
    return value.strftime("%Y-%m")


def quarter_group(value: date) -> str:
    """Group dates into calendar quarters."""
    quarter = (value.month - 1) // 3 + 1
    return f"{value.year}-Q{quarter}"


def year_group(value: date) -> int:
    """Group dates into calendar years."""
    return value.year


def quantity_band(quantity: int) -> str:
    """
    Numeric grouping example.

    Excel users can group numeric values into intervals.
    """
    if quantity <= 2:
        return "1-2"
    if quantity <= 5:
        return "3-5"
    if quantity <= 8:
        return "6-8"
    return "9+"


def grouped_value(
    record: SalesRecord,
    field_name: str,
    grouping: Optional[str] = None,
) -> Any:
    value = field_value(record, field_name)

    if grouping is None:
        return value

    if grouping == "month":
        if not isinstance(value, date):
            raise TypeError("Month grouping requires a date field.")
        return month_group(value)

    if grouping == "quarter":
        if not isinstance(value, date):
            raise TypeError("Quarter grouping requires a date field.")
        return quarter_group(value)

    if grouping == "year":
        if not isinstance(value, date):
            raise TypeError("Year grouping requires a date field.")
        return year_group(value)

    if grouping == "quantity_band":
        if not isinstance(value, int):
            raise TypeError("Quantity-band grouping requires an integer.")
        return quantity_band(value)

    raise ValueError(f"Unknown grouping mode: {grouping}")


# ---------------------------------------------------------------------------
# 9. PIVOT RESULT
# ---------------------------------------------------------------------------

@dataclass
class PivotResult:
    """
    Stores the summarized cells of a Pivot Table.

    Each cell is identified by:
        row key
        column key

    Example:
        ("North",) + ("Laptop",)
    """

    cells: dict[tuple[Any, ...], dict[tuple[Any, ...], dict[str, Any]]]
    row_keys: list[tuple[Any, ...]]
    column_keys: list[tuple[Any, ...]]
    grand_totals: dict[str, Any]


# ---------------------------------------------------------------------------
# 10. PIVOT ENGINE
# ---------------------------------------------------------------------------

class PivotEngine:
    """
    A reusable Excel-style Pivot Table engine.

    This is not an attempt to reproduce Excel's internal implementation.
    Instead, it exposes the fundamental conceptual operations:

        source data
            ↓
        filters
            ↓
        dimensions
            ↓
        grouping
            ↓
        aggregation
            ↓
        summarized matrix
    """

    def __init__(self, records: list[SalesRecord]) -> None:
        self.records = records

    def validate_configuration(self, config: PivotConfiguration) -> None:
        if not config.values:
            raise ValueError(
                "A Pivot Table needs at least one value field "
                "for meaningful numeric summarization."
            )

        valid_fields = {
            "order_date",
            "region",
            "salesperson",
            "product",
            "category",
            "quantity",
            "unit_price",
            "unit_cost",
            "sales",
            "revenue",
            "cost",
            "profit",
            "profit_margin",
            "customer_type",
        }

        requested = (
            config.rows
            + config.columns
            + list(config.filters.keys())
            + [value.field for value in config.values]
        )

        unknown = [
            item for item in requested
            if item.lower().replace(" ", "_") not in valid_fields
            and item not in config.calculated_fields
        ]

        if unknown:
            raise ValueError(f"Unknown Pivot field(s): {unknown}")

    def calculate_value(
        self,
        record: SalesRecord,
        value_field_name: str,
        calculated_fields: dict[str, Callable[[SalesRecord], Any]],
    ) -> Any:
        if value_field_name in calculated_fields:
            return calculated_fields[value_field_name](record)

        return field_value(record, value_field_name)

    def build(
        self,
        config: PivotConfiguration,
        row_grouping: Optional[dict[str, str]] = None,
        column_grouping: Optional[dict[str, str]] = None,
        sort_rows: bool = True,
        sort_columns: bool = True,
    ) -> PivotResult:
        self.validate_configuration(config)

        row_grouping = row_grouping or {}
        column_grouping = column_grouping or {}

        records = apply_filters(self.records, config.filters)

        cells: dict[
            tuple[Any, ...],
            dict[tuple[Any, ...], dict[str, list[Any]]]
        ] = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))

        row_keys_set: set[tuple[Any, ...]] = set()
        column_keys_set: set[tuple[Any, ...]] = set()

        for record in records:
            row_key = tuple(
                grouped_value(
                    record,
                    field_name,
                    row_grouping.get(field_name),
                )
                for field_name in config.rows
            )

            column_key = tuple(
                grouped_value(
                    record,
                    field_name,
                    column_grouping.get(field_name),
                )
                for field_name in config.columns
            )

            row_keys_set.add(row_key)
            column_keys_set.add(column_key)

            for value_field in config.values:
                value = self.calculate_value(
                    record,
                    value_field.field,
                    config.calculated_fields,
                )

                cells[row_key][column_key][value_field.label].append(value)

        row_keys = sorted(row_keys_set) if sort_rows else list(row_keys_set)
        column_keys = (
            sorted(column_keys_set)
            if sort_columns
            else list(column_keys_set)
        )

        summarized: dict[
            tuple[Any, ...],
            dict[tuple[Any, ...], dict[str, Any]]
        ] = defaultdict(dict)

        for row_key in row_keys:
            for column_key in column_keys:
                raw_values = cells[row_key][column_key]

                if not raw_values:
                    continue

                summarized[row_key][column_key] = {}

                for value_field in config.values:
                    values = raw_values[value_field.label]
                    function = AGGREGATIONS[value_field.aggregation]
                    summarized[row_key][column_key][value_field.label] = function(
                        values
                    )

        grand_totals: dict[str, Any] = {}

        for value_field in config.values:
            all_values: list[Any] = []

            for row_cells in cells.values():
                for cell in row_cells.values():
                    all_values.extend(cell[value_field.label])

            function = AGGREGATIONS[value_field.aggregation]
            grand_totals[value_field.label] = function(all_values)

        return PivotResult(
            cells=dict(summarized),
            row_keys=row_keys,
            column_keys=column_keys,
            grand_totals=grand_totals,
        )


# ---------------------------------------------------------------------------
# 11. FORMATTING PIVOT RESULTS
# ---------------------------------------------------------------------------

def format_number(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, float):
        return f"{value:,.2f}"
    if isinstance(value, int):
        return f"{value:,}"
    return str(value)


def print_pivot(result: PivotResult, title: str) -> None:
    print("\n" + "=" * 90)
    print(title)
    print("=" * 90)

    if not result.row_keys:
        print("No rows matched the selected filters.")
        return

    if not result.column_keys:
        print("No columns matched the selected filters.")
        return

    print("Rows:", result.row_keys)
    print("Columns:", result.column_keys)

    for row_key in result.row_keys:
        print(f"\nRow: {row_key}")

        row_cells = result.cells.get(row_key, {})

        for column_key in result.column_keys:
            cell = row_cells.get(column_key)

            if cell is None:
                print(f"  {column_key}: no records")
            else:
                values = ", ".join(
                    f"{label}={format_number(value)}"
                    for label, value in cell.items()
                )
                print(f"  {column_key}: {values}")

    print("\nGrand Totals:")
    for label, value in result.grand_totals.items():
        print(f"  {label}: {format_number(value)}")


# ---------------------------------------------------------------------------
# 12. EXAMPLE 1: BASIC PIVOT
# ---------------------------------------------------------------------------
#
# Rows = Region
# Values = SUM(Sales)
#
# This is the simplest meaningful Pivot Table.


engine = PivotEngine(DATA)

basic_config = PivotConfiguration(
    rows=["region"],
    values=[
        ValueField("sales", "sum", "Total Sales"),
    ],
)

basic_result = engine.build(basic_config)
print_pivot(
    basic_result,
    "Example 1 - Sales by Region",
)


# ---------------------------------------------------------------------------
# 13. EXAMPLE 2: ROWS + COLUMNS
# ---------------------------------------------------------------------------
#
# Rows = Region
# Columns = Product
# Values = SUM(Sales)
#
# This produces a two-dimensional analytical matrix.


row_column_config = PivotConfiguration(
    rows=["region"],
    columns=["product"],
    values=[
        ValueField("sales", "sum", "Total Sales"),
    ],
)

row_column_result = engine.build(row_column_config)

print_pivot(
    row_column_result,
    "Example 2 - Sales by Region and Product",
)


# ---------------------------------------------------------------------------
# 14. EXAMPLE 3: MULTIPLE VALUE FIELDS
# ---------------------------------------------------------------------------
#
# A Pivot Table can contain multiple measures.
#
# Values:
#   SUM(Sales)
#   SUM(Profit)
#   AVERAGE(Quantity)
#   COUNT(Order ID conceptually represented by records)
#
# This allows several business questions to be answered from the same
# dimensional layout.


multi_value_config = PivotConfiguration(
    rows=["category"],
    values=[
        ValueField("sales", "sum", "Total Sales"),
        ValueField("profit", "sum", "Total Profit"),
        ValueField("quantity", "average", "Average Quantity"),
        ValueField("sales", "count", "Transaction Count"),
    ],
)

multi_value_result = engine.build(multi_value_config)

print_pivot(
    multi_value_result,
    "Example 3 - Multiple Value Fields by Category",
)


# ---------------------------------------------------------------------------
# 15. EXAMPLE 4: REPORT FILTERS
# ---------------------------------------------------------------------------
#
# Filters restrict source records before aggregation.
#
# Region = North or South
# Customer Type = Corporate


filtered_config = PivotConfiguration(
    rows=["product"],
    values=[
        ValueField("sales", "sum", "Corporate Sales"),
        ValueField("profit", "sum", "Corporate Profit"),
    ],
    filters={
        "region": {"North", "South"},
        "customer_type": {"Corporate"},
    },
)

filtered_result = engine.build(filtered_config)

print_pivot(
    filtered_result,
    "Example 4 - Corporate Sales for North and South",
)


# ---------------------------------------------------------------------------
# 16. EXAMPLE 5: DATE GROUPING
# ---------------------------------------------------------------------------
#
# Excel can group dates into:
#   Years
#   Quarters
#   Months
#
# The exact options depend on the source data and Pivot Table context.


monthly_config = PivotConfiguration(
    rows=["order_date"],
    values=[
        ValueField("sales", "sum", "Monthly Sales"),
    ],
)

monthly_result = engine.build(
    monthly_config,
    row_grouping={"order_date": "month"},
)

print_pivot(
    monthly_result,
    "Example 5 - Monthly Sales",
)


quarterly_config = PivotConfiguration(
    rows=["order_date"],
    values=[
        ValueField("sales", "sum", "Quarterly Sales"),
    ],
)

quarterly_result = engine.build(
    quarterly_config,
    row_grouping={"order_date": "quarter"},
)

print_pivot(
    quarterly_result,
    "Example 5B - Quarterly Sales",
)


# ---------------------------------------------------------------------------
# 17. EXAMPLE 6: CALCULATED FIELDS
# ---------------------------------------------------------------------------
#
# A calculated field can derive a business measure from source fields.
#
# Profit = Sales - Cost
# Margin = Profit / Sales
#
# The Python implementation makes the calculation function explicit so that
# the evaluation process is easy to inspect.


calculated_config = PivotConfiguration(
    rows=["region"],
    values=[
        ValueField("sales", "sum", "Total Sales"),
        ValueField("profit_calculated", "sum", "Calculated Profit"),
        ValueField("margin_calculated", "average", "Average Margin"),
    ],
    calculated_fields={
        "profit_calculated": calculated_profit,
        "margin_calculated": calculated_margin,
    },
)

calculated_result = engine.build(calculated_config)

print_pivot(
    calculated_result,
    "Example 6 - Calculated Profit and Margin",
)


# ---------------------------------------------------------------------------
# 18. EXAMPLE 7: NUMERIC GROUPING
# ---------------------------------------------------------------------------
#
# Numeric values can be grouped into ranges.
#
# Quantity:
#   1-2
#   3-5
#   6-8
#   9+
#
# This is useful for distribution analysis.


quantity_group_config = PivotConfiguration(
    rows=["quantity"],
    values=[
        ValueField("sales", "sum", "Sales by Quantity Band"),
        ValueField("quantity", "count", "Transaction Count"),
    ],
)

quantity_group_result = engine.build(
    quantity_group_config,
    row_grouping={"quantity": "quantity_band"},
)

print_pivot(
    quantity_group_result,
    "Example 7 - Sales by Quantity Band",
)


# ---------------------------------------------------------------------------
# 19. EXAMPLE 8: SUBTOTAL CONCEPT
# ---------------------------------------------------------------------------
#
# Excel can display subtotals when multiple row fields are used.
#
# Example:
#   Category
#       Product
#
# The engine below explicitly computes subtotals to show the underlying
# aggregation idea.


def subtotal_by_dimension(
    records: list[SalesRecord],
    dimension: str,
    measure: str = "sales",
) -> dict[Any, float]:
    totals: defaultdict[Any, float] = defaultdict(float)

    for record in records:
        totals[field_value(record, dimension)] += field_value(record, measure)

    return dict(totals)


category_subtotals = subtotal_by_dimension(DATA, "category", "sales")

print("\n" + "=" * 90)
print("Example 8 - Category Subtotals")
print("=" * 90)

for category, total in sorted(category_subtotals.items()):
    print(f"{category}: {total:,.2f}")


# ---------------------------------------------------------------------------
# 20. EXAMPLE 9: GRAND TOTAL
# ---------------------------------------------------------------------------
#
# The grand total is an aggregation across all relevant records.
#
# It is not simply "another row". It represents the aggregate of the entire
# filtered dataset for the selected value field.


grand_total_sales = aggregate_sum(record.sales for record in DATA)
grand_total_profit = aggregate_sum(record.profit for record in DATA)

print("\n" + "=" * 90)
print("Example 9 - Grand Totals")
print("=" * 90)
print(f"Grand Total Sales:  {grand_total_sales:,.2f}")
print(f"Grand Total Profit: {grand_total_profit:,.2f}")


# ---------------------------------------------------------------------------
# 21. DRILL-DOWN
# ---------------------------------------------------------------------------
#
# One of the most useful Pivot Table behaviors is drill-down.
#
# When a user double-clicks a summarized Pivot Table value in Excel, Excel can
# create a new worksheet containing the underlying records contributing to
# that cell.
#
# The function below demonstrates the same logical operation.


def drill_down(
    records: list[SalesRecord],
    row_field: str,
    row_value: Any,
    column_field: Optional[str] = None,
    column_value: Optional[Any] = None,
) -> list[SalesRecord]:
    """
    Return source records contributing to a selected Pivot cell.
    """
    selected = []

    for record in records:
        if field_value(record, row_field) != row_value:
            continue

        if column_field is not None:
            if field_value(record, column_field) != column_value:
                continue

        selected.append(record)

    return selected


north_laptop_records = drill_down(
    DATA,
    row_field="region",
    row_value="North",
    column_field="product",
    column_value="Laptop",
)

print("\n" + "=" * 90)
print("Example 10 - Drill-Down: North + Laptop")
print("=" * 90)

for record in north_laptop_records:
    print(
        record.order_id,
        record.order_date,
        record.region,
        record.product,
        record.quantity,
        f"sales={record.sales:,.2f}",
        f"profit={record.profit:,.2f}",
    )


# ---------------------------------------------------------------------------
# 22. EDGE CASES
# ---------------------------------------------------------------------------

EDGE_CASE_DATA = [
    SalesRecord(
        "E001",
        date(2025, 9, 1),
        "North",
        "Test",
        "ZeroPrice",
        "Test",
        5,
        0,
        0,
        "Retail",
    ),
    SalesRecord(
        "E002",
        date(2025, 9, 2),
        "North",
        "Test",
        "ZeroQuantity",
        "Test",
        0,
        100,
        60,
        "Retail",
    ),
]


edge_engine = PivotEngine(EDGE_CASE_DATA)

edge_config = PivotConfiguration(
    rows=["product"],
    values=[
        ValueField("sales", "sum", "Sales"),
        ValueField("profit_margin", "average", "Average Margin"),
    ],
)

edge_result = edge_engine.build(edge_config)

print_pivot(
    edge_result,
    "Example 11 - Edge Cases: Zero Quantity and Zero Sales",
)


# ---------------------------------------------------------------------------
# 23. MISSING DATA CONCEPT
# ---------------------------------------------------------------------------
#
# Real Excel source tables frequently contain blanks.
#
# Important distinction:
#   blank numeric value
#   zero
#   text
#   missing category
#
# These should not automatically be treated as identical.
#
# Our source model normally uses explicit values. The helper below demonstrates
# safe handling when values are missing.


def safe_numeric_sum(values: Iterable[Optional[float]]) -> float:
    """
    Ignore None values while preserving zero as a legitimate numeric value.
    """
    return sum(value for value in values if value is not None)


print("\n" + "=" * 90)
print("Example 12 - Missing Values")
print("=" * 90)
print(
    "SUM([100, None, 0, 50]) =",
    safe_numeric_sum([100, None, 0, 50]),
)


# ---------------------------------------------------------------------------
# 24. COUNT VS DISTINCT COUNT
# ---------------------------------------------------------------------------
#
# COUNT measures the number of observations.
#
# DISTINCT COUNT measures unique entities.
#
# Example:
#   Orders: O001, O002, O002, O003
#
# COUNT = 4
# DISTINCT COUNT = 3
#
# In Excel, distinct count is associated with the Data Model / Power Pivot
# workflow rather than being identical to ordinary Pivot Table counting.


sample_orders = ["O001", "O002", "O002", "O003"]

print("\n" + "=" * 90)
print("Example 13 - COUNT vs DISTINCT COUNT")
print("=" * 90)
print("COUNT:", len(sample_orders))
print("DISTINCT COUNT:", len(set(sample_orders)))


# ---------------------------------------------------------------------------
# 25. SORTING
# ---------------------------------------------------------------------------
#
# Pivot results can be sorted by:
#   - Labels
#   - Values
#   - Custom business ordering
#
# The engine's basic implementation sorts dimension keys naturally.
#
# A value-based ranking is shown below.


region_sales = subtotal_by_dimension(DATA, "region", "sales")

ranked_regions = sorted(
    region_sales.items(),
    key=lambda item: item[1],
    reverse=True,
)

print("\n" + "=" * 90)
print("Example 14 - Regions Ranked by Sales")
print("=" * 90)

for rank, (region, sales) in enumerate(ranked_regions, start=1):
    print(f"{rank}. {region}: {sales:,.2f}")


# ---------------------------------------------------------------------------
# 26. PERCENTAGE-OF-TOTAL ANALYSIS
# ---------------------------------------------------------------------------
#
# A common Pivot Table analysis is:
#
#     category sales / grand total sales
#
# This is conceptually related to Excel's "Show Values As" functionality.


category_sales = subtotal_by_dimension(DATA, "category", "sales")
total_sales = sum(category_sales.values())

print("\n" + "=" * 90)
print("Example 15 - Percentage of Grand Total")
print("=" * 90)

for category, sales in sorted(category_sales.items()):
    percentage = (sales / total_sales * 100) if total_sales else 0
    print(
        f"{category}: "
        f"{sales:,.2f} "
        f"({percentage:.2f}% of total)"
    )


# ---------------------------------------------------------------------------
# 27. RUNNING TOTAL CONCEPT
# ---------------------------------------------------------------------------
#
# Another common Pivot Table presentation is a running total over time.


monthly_sales: dict[str, float] = defaultdict(float)

for record in DATA:
    monthly_sales[month_group(record.order_date)] += record.sales

running_total = 0.0

print("\n" + "=" * 90)
print("Example 16 - Running Total by Month")
print("=" * 90)

for month, sales in sorted(monthly_sales.items()):
    running_total += sales
    print(
        f"{month}: "
        f"monthly={sales:,.2f}, "
        f"running={running_total:,.2f}"
    )


# ---------------------------------------------------------------------------
# 28. TOP-N ANALYSIS
# ---------------------------------------------------------------------------
#
# Pivot Tables are frequently used to identify top products, regions, or
# customers.


product_sales = subtotal_by_dimension(DATA, "product", "sales")

top_three_products = sorted(
    product_sales.items(),
    key=lambda item: item[1],
    reverse=True,
)[:3]

print("\n" + "=" * 90)
print("Example 17 - Top Three Products")
print("=" * 90)

for product, sales in top_three_products:
    print(f"{product}: {sales:,.2f}")


# ---------------------------------------------------------------------------
# 29. VALIDATION
# ---------------------------------------------------------------------------
#
# A Pivot Table is only as reliable as the source data.
#
# Common source-data problems:
#   - Duplicate records
#   - Incorrect headers
#   - Mixed data types
#   - Blank categories
#   - Numbers stored as text
#   - Dates stored as text
#   - Inconsistent spellings
#   - Formula errors
#
# The validator below demonstrates basic checks.


def validate_source(records: list[SalesRecord]) -> list[str]:
    errors: list[str] = []

    order_ids: set[str] = set()

    for record in records:
        if not record.order_id:
            errors.append("A record has a blank order ID.")

        if record.order_id in order_ids:
            errors.append(f"Duplicate order ID: {record.order_id}")

        order_ids.add(record.order_id)

        if record.quantity < 0:
            errors.append(
                f"Negative quantity for {record.order_id}."
            )

        if record.unit_price < 0:
            errors.append(
                f"Negative unit price for {record.order_id}."
            )

        if record.unit_cost < 0:
            errors.append(
                f"Negative unit cost for {record.order_id}."
            )

        if not record.region:
            errors.append(
                f"Blank region for {record.order_id}."
            )

    return errors


validation_errors = validate_source(DATA)

print("\n" + "=" * 90)
print("Example 18 - Source Validation")
print("=" * 90)

if validation_errors:
    for error in validation_errors:
        print("ERROR:", error)
else:
    print("Source data passed basic validation.")


# ---------------------------------------------------------------------------
# 30. DUPLICATE DETECTION
# ---------------------------------------------------------------------------

def find_duplicate_order_ids(
    records: list[SalesRecord],
) -> list[str]:
    counts = defaultdict(int)

    for record in records:
        counts[record.order_id] += 1

    return sorted(
        order_id
        for order_id, count in counts.items()
        if count > 1
    )


print("\n" + "=" * 90)
print("Example 19 - Duplicate Detection")
print("=" * 90)
print(
    "Duplicate order IDs:",
    find_duplicate_order_ids(DATA),
)


# ---------------------------------------------------------------------------
# 31. PIVOT ARCHITECTURE AS A DATA PIPELINE
# ---------------------------------------------------------------------------
#
# The important conceptual pipeline is:
#
#     source table
#          |
#          v
#       filtering
#          |
#          v
#       grouping keys
#          |
#          v
#      aggregation
#          |
#          v
#      Pivot cells
#          |
#          +----> subtotals
#          |
#          +----> grand totals
#          |
#          +----> drill-down
#
# This resembles a GROUP BY operation in SQL.
#
# SQL conceptual equivalent:
#
#     SELECT region, product, SUM(sales)
#     FROM sales
#     GROUP BY region, product;
#
# Pivot Tables provide a user-oriented multidimensional interface around
# related aggregation operations.


def sql_like_group_by(
    records: Iterable[SalesRecord],
    dimensions: list[str],
    measure: str,
) -> dict[tuple[Any, ...], float]:
    result: defaultdict[tuple[Any, ...], float] = defaultdict(float)

    for record in records:
        key = tuple(
            field_value(record, dimension)
            for dimension in dimensions
        )
        result[key] += field_value(record, measure)

    return dict(result)


sql_like_result = sql_like_group_by(
    DATA,
    ["region", "product"],
    "sales",
)

print("\n" + "=" * 90)
print("Example 20 - SQL GROUP BY Concept")
print("=" * 90)

for key, total in sorted(sql_like_result.items()):
    print(f"{key}: {total:,.2f}")


# ---------------------------------------------------------------------------
# 32. PERFORMANCE CONSIDERATIONS
# ---------------------------------------------------------------------------
#
# Let:
#   N = number of source records
#   R = number of distinct row keys
#   C = number of distinct column keys
#   V = number of value fields
#
# A straightforward pivot pass is approximately O(N * V) for constructing
# aggregates, plus sorting costs.
#
# Memory depends on:
#   - number of unique dimensions
#   - number of cells
#   - number of measures
#
# For large datasets, storing every raw value for every aggregation is less
# memory-efficient than maintaining streaming accumulators.
#
# The demonstration below shows a streaming SUM calculation.


def streaming_sum_by_dimension(
    records: Iterable[SalesRecord],
    dimension: str,
    measure: str,
) -> dict[Any, float]:
    totals: defaultdict[Any, float] = defaultdict(float)

    for record in records:
        key = field_value(record, dimension)
        value = field_value(record, measure)
        totals[key] += value

    return dict(totals)


print("\n" + "=" * 90)
print("Example 21 - Streaming Aggregation")
print("=" * 90)

print(
    streaming_sum_by_dimension(
        DATA,
        "region",
        "sales",
    )
)


# ---------------------------------------------------------------------------
# 33. MEMORY-EFFICIENT AVERAGE
# ---------------------------------------------------------------------------
#
# Average can also be calculated without retaining every observation:
#
#     average = sum / count
#
# This is an important implementation technique for large datasets.


def streaming_average(
    values: Iterable[float],
) -> float:
    total = 0.0
    count = 0

    for value in values:
        total += value
        count += 1

    return total / count if count else 0.0


print("\n" + "=" * 90)
print("Example 22 - Streaming Average")
print("=" * 90)

print(
    streaming_average(
        record.quantity for record in DATA
    )
)


# ---------------------------------------------------------------------------
# 34. PIVOT DESIGN BEST PRACTICES
# ---------------------------------------------------------------------------
#
# Practical rules:
#
# 1. Keep source data tabular.
# 2. Use one header row.
# 3. Avoid merged cells in the source range.
# 4. Keep each column to one logical variable.
# 5. Store dates as real dates.
# 6. Store numbers as numeric values.
# 7. Avoid manual totals inside the source table.
# 8. Prefer Excel Tables as dynamic source ranges.
# 9. Refresh the Pivot Table after source changes.
# 10. Verify aggregation type, especially SUM vs COUNT.
# 11. Check blanks and inconsistent labels.
# 12. Use grouping carefully when dates contain invalid values.
# 13. Document calculated fields.
# 14. Validate totals against the source data.
# 15. Avoid overly complicated Pivot layouts when a simpler layout answers
#     the business question.


# ---------------------------------------------------------------------------
# 35. COMMON MISTAKE DEMONSTRATION
# ---------------------------------------------------------------------------
#
# If a numeric column contains text-like values, a real spreadsheet may not
# aggregate the field as expected.
#
# Python demonstrates the conceptual problem:


mixed_numeric_data = [100, 200, "300", 400]

print("\n" + "=" * 90)
print("Example 23 - Mixed Data Types")
print("=" * 90)

try:
    print(sum(mixed_numeric_data))
except TypeError as error:
    print("Aggregation failed because the data types are inconsistent.")
    print("Error:", error)


# ---------------------------------------------------------------------------
# 36. SAFE NUMERIC NORMALIZATION
# ---------------------------------------------------------------------------

def normalize_numeric(value: Any) -> Optional[float]:
    """
    Convert reasonable numeric input to float.

    This is analogous to cleaning imported spreadsheet data before building
    a Pivot Table.
    """
    if value is None:
        return None

    if isinstance(value, bool):
        return None

    if isinstance(value, (int, float)):
        return float(value)

    if isinstance(value, str):
        cleaned = value.strip().replace(",", "")

        if not cleaned:
            return None

        try:
            return float(cleaned)
        except ValueError:
            return None

    return None


normalized_values = [
    normalize_numeric(value)
    for value in mixed_numeric_data
]

print("\n" + "=" * 90)
print("Example 24 - Data Normalization")
print("=" * 90)
print(normalized_values)


# ---------------------------------------------------------------------------
# 37. REUSABLE BUSINESS REPORT
# ---------------------------------------------------------------------------

def build_management_report(records: list[SalesRecord]) -> dict[str, Any]:
    """
    Build several Pivot-style management metrics from one source dataset.
    """

    total_sales = sum(record.sales for record in records)
    total_profit = sum(record.profit for record in records)
    total_quantity = sum(record.quantity for record in records)

    region_sales = streaming_sum_by_dimension(
        records,
        "region",
        "sales",
    )

    category_sales = streaming_sum_by_dimension(
        records,
        "category",
        "sales",
    )

    product_sales = streaming_sum_by_dimension(
        records,
        "product",
        "sales",
    )

    average_order_value = (
        total_sales / len(records)
        if records
        else 0.0
    )

    profit_margin = (
        total_profit / total_sales
        if total_sales
        else 0.0
    )

    return {
        "total_sales": total_sales,
        "total_profit": total_profit,
        "total_quantity": total_quantity,
        "transaction_count": len(records),
        "average_order_value": average_order_value,
        "profit_margin": profit_margin,
        "sales_by_region": region_sales,
        "sales_by_category": category_sales,
        "sales_by_product": product_sales,
    }


management_report = build_management_report(DATA)

print("\n" + "=" * 90)
print("Example 25 - Management Pivot Report")
print("=" * 90)

for key, value in management_report.items():
    print(f"{key}: {value}")


# ---------------------------------------------------------------------------
# 38. SECURITY AND GOVERNANCE CONSIDERATIONS
# ---------------------------------------------------------------------------
#
# Pivot Tables themselves are primarily analytical objects, but security still
# matters when the source contains sensitive information.
#
# Important considerations:
#
#   - A Pivot Table may reveal sensitive totals even when raw rows are hidden.
#   - Drill-down can expose source records.
#   - Workbook permissions do not automatically make analytical outputs safe.
#   - Personally identifiable information should not be unnecessarily included
#     in source data.
#   - External data connections should be reviewed.
#   - Refresh credentials and connection settings require appropriate access.
#   - A copied Pivot Table can preserve information from the source.
#
# The code does not implement workbook security because those are Excel
# application-level concerns.


# ---------------------------------------------------------------------------
# 39. ADVANCED COMPARISON: PIVOT TABLE VS SQL GROUP BY
# ---------------------------------------------------------------------------
#
# Pivot Table:
#   - Interactive
#   - Spreadsheet-oriented
#   - Strong for exploratory reporting
#   - Easy for business users
#   - Supports drag-and-drop dimensions
#
# SQL GROUP BY:
#   - Declarative query language
#   - Strong for database-side aggregation
#   - Reproducible queries
#   - Better suited to automated data pipelines
#
# Pandas pivot_table:
#   - Programmatic analysis
#   - Flexible data manipulation
#   - Useful for Python analytics
#
# Power Pivot / Data Model:
#   - Designed for larger analytical models
#   - Supports relationships
#   - Uses DAX for advanced measures
#
# These technologies overlap conceptually but solve different workflow needs.


# ---------------------------------------------------------------------------
# 40. TESTS
# ---------------------------------------------------------------------------

def test_sales_calculation() -> None:
    record = SalesRecord(
        "T001",
        date(2025, 1, 1),
        "Test",
        "Tester",
        "Product",
        "Category",
        3,
        100,
        60,
        "Retail",
    )

    assert record.sales == 300
    assert record.cost == 180
    assert record.profit == 120


def test_filtering() -> None:
    records = apply_filters(
        DATA,
        {"region": {"North"}},
    )

    assert records
    assert all(record.region == "North" for record in records)


def test_pivot_grand_total() -> None:
    config = PivotConfiguration(
        rows=["region"],
        values=[
            ValueField("sales", "sum", "Sales"),
        ],
    )

    result = engine.build(config)

    expected = sum(record.sales for record in DATA)

    assert abs(result.grand_totals["Sales"] - expected) < 1e-9


def test_drill_down() -> None:
    records = drill_down(
        DATA,
        "region",
        "North",
    )

    assert records
    assert all(record.region == "North" for record in records)


def run_tests() -> None:
    test_sales_calculation()
    test_filtering()
    test_pivot_grand_total()
    test_drill_down()
    print("\nAll tests passed.")


run_tests()


# ---------------------------------------------------------------------------
# 41. FINAL CONCEPTUAL DEMONSTRATION
# ---------------------------------------------------------------------------
#
# The following configuration combines several major Pivot concepts:
#
#   Filter:
#       Corporate customers
#
#   Rows:
#       Region
#
#   Columns:
#       Category
#
#   Values:
#       Total Sales
#       Total Profit
#
#   Grouping:
#       None in this example
#
#   Calculated Field:
#       Profit is derived from Sales - Cost
#
#   Output:
#       A multidimensional business report


advanced_config = PivotConfiguration(
    rows=["region"],
    columns=["category"],
    values=[
        ValueField("sales", "sum", "Total Sales"),
        ValueField("profit_calculated", "sum", "Total Profit"),
    ],
    filters={
        "customer_type": {"Corporate"},
    },
    calculated_fields={
        "profit_calculated": calculated_profit,
    },
)

advanced_result = engine.build(advanced_config)

print_pivot(
    advanced_result,
    "Example 26 - Advanced Corporate Management Pivot",
)


# ---------------------------------------------------------------------------
# 42. STUDY CHECKLIST
# ---------------------------------------------------------------------------
#
# The following executable data structure acts as a compact revision checklist.
#
# It is deliberately represented as Python data so it can be inspected,
# modified, tested, or incorporated into another educational program.


STUDY_CHECKLIST = {
    "fundamentals": [
        "Source data",
        "Rows",
        "Columns",
        "Values",
        "Filters",
        "Aggregation",
    ],
    "intermediate": [
        "Multiple value fields",
        "Sorting",
        "Subtotals",
        "Grand totals",
        "Date grouping",
        "Numeric grouping",
        "Calculated fields",
        "Drill-down",
    ],
    "advanced": [
        "Distinct count",
        "Percentage of total",
        "Running totals",
        "Top-N analysis",
        "Streaming aggregation",
        "Data validation",
        "Performance analysis",
        "Security and governance",
        "SQL GROUP BY relationship",
        "Data Model distinction",
    ],
}

print("\n" + "=" * 90)
print("Study Checklist")
print("=" * 90)

for level, concepts in STUDY_CHECKLIST.items():
    print(f"\n{level.upper()}")
    for concept in concepts:
        print(f"  - {concept}")


# ---------------------------------------------------------------------------
# END OF SCRIPT
# ---------------------------------------------------------------------------
#
# Important conceptual distinction:
#
# A Pivot Table is not simply a formatted table.
#
# Its core function is multidimensional aggregation:
#
#     dimensions + measures + filters + grouping
#                         ↓
#                    summarized view
#
# Drill-down reverses the abstraction for a selected cell by exposing the
# source records contributing to that summary.
#
# This relationship between raw records and summarized dimensions is the
# central idea behind Pivot Table architecture.
